/**
 * GENERATED by tools/legacy-import/build-image-registry.mjs — do not edit.
 * Run `pnpm migrate:images` after adding or replacing an asset.
 */

export type ImageDimensions = { width: number; height: number };

export const IMAGE_REGISTRY = {
  '/assets/0661_Marsa_Al_Arab_Iliana_2_829970fd.webp': { width: 1706, height: 2560 },
  '/assets/0662_Waldorf_Astoria_Osaka_13_c71bc2ac.webp': { width: 2560, height: 1440 },
  '/assets/0663_Marsa_Al_Arab_Suite1_7_a51be4a1.webp': { width: 1706, height: 2560 },
  '/assets/0664_Marsa_Al_Arab_Suite2_4_78452d9c.webp': { width: 1706, height: 2560 },
  '/assets/0667_Marsa_Al_Arab_Lobby_9_dff7cff7.webp': { width: 1706, height: 2560 },
  '/assets/0669_Waldorf_Astoria_Osaka_18_536d1f9e.webp': { width: 2560, height: 1707 },
  '/assets/0670_Marsa_Al_Arab_Bombay_5_95764db5.webp': { width: 1706, height: 2560 },
  '/assets/0672_Marsa_Al_Arab_Lobby_10_4fff97ed.webp': { width: 1706, height: 2560 },
  '/assets/0674_Marsa_Al_Arab_Suite1_1_49bd6513.webp': { width: 1706, height: 2560 },
  '/assets/0676_Marsa_Al_Arab_Lobby_5_b2051520.webp': { width: 1706, height: 2560 },
  '/assets/0678_Marsa_Al_Arab_Lobby_4_b7af1dee.webp': { width: 1706, height: 2560 },
  '/assets/0679_Marsa_Al_Arab_Bombay_3_09aae676.webp': { width: 1706, height: 2560 },
  '/assets/0680_Marsa_Al_Arab_Iliana_3_e20bcd92.webp': { width: 1706, height: 2560 },
  '/assets/0681_Marsa_Al_Arab_Lobby_2_d21675ab.webp': { width: 1706, height: 2560 },
  '/assets/0682_Waldorf_Astoria_Osaka_12_ef1532bb.webp': { width: 2560, height: 1707 },
  '/assets/0685_Marsa_Al_Arab_Lobby_11_c9061482.webp': { width: 1706, height: 2560 },
  '/assets/0686_Waldorf_Astoria_Osaka_16_948b5f8c.webp': { width: 2560, height: 1707 },
  '/assets/0687_Marsa_Al_Arab_Lobby_8_25ea7574.webp': { width: 1706, height: 2560 },
  '/assets/0689_Marsa_Al_Arab_Iliana_5_0c49bd95.webp': { width: 1706, height: 2560 },
  '/assets/0692_Get_in_touch_7b21b857.webp': { width: 866, height: 500 },
  '/assets/0694_27I6900-6copy_51177df8.webp': { width: 2048, height: 1365 },
  '/assets/0698_Finer_Living_July_2025_edited_1_a006768d.webp': { width: 2560, height: 1706 },
  '/assets/1.webp': { width: 2048, height: 1606 },
  '/assets/2.webp': { width: 2048, height: 1365 },
  '/assets/3.webp': { width: 2048, height: 1365 },
  '/assets/favicon.png': { width: 844, height: 1000 },
  '/assets/finer-things-family.webp': { width: 1170, height: 1463 },
  '/assets/finer-things-logo.png': { width: 1080, height: 242 },
  '/assets/hero1.webp': { width: 1500, height: 1363 },
  '/assets/hero2.webp': { width: 1414, height: 1899 },
  '/assets/hero3.webp': { width: 600, height: 578 },
  '/assets/hero4.webp': { width: 1406, height: 1412 },
  '/assets/hero5.webp': { width: 1500, height: 1372 },
  '/assets/hero6.webp': { width: 1500, height: 1290 },
  '/assets/hero7.webp': { width: 1440, height: 1000 },
} as const satisfies Record<string, ImageDimensions>;

export type RegisteredImage = keyof typeof IMAGE_REGISTRY;

/**
 * Intrinsic size lookup. Throws at build time on an unknown path so a typo in
 * an asset name can never ship as a silently broken image.
 */
export function imageSize(src: RegisteredImage): ImageDimensions {
  const size = IMAGE_REGISTRY[src];
  if (!size) throw new Error(`Unknown image asset: ${src}`);
  return size;
}
